sonar.projectKey=davydfontourac_davydfontoura-dev
sonar.organization=davydfontourac
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/setupTests.js